"""
Finalization script (auto-generated by assistant):
* Ensures DB helper exists
* Ensures Redis client
* Creates HybridFeedEngine service if missing
* Creates simple AIModerationService placeholder
* Writes Flutter config
* Creates verification script
* Runs quick checks
"""
import os
import sys
import subprocess
import traceback
from pathlib import Path

ROOT = Path(__file__).resolve().parent
os.chdir(ROOT)

print("ROOT:", ROOT)


def sh(cmd, check=True):
    print("RUN >", cmd)
    res = subprocess.run(cmd, shell=True, check=False, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    print(res.stdout)
    if check and res.returncode != 0:
        raise RuntimeError(f"Command failed: {cmd}\nOutput:\n{res.stdout}")
    return res

# 1) Ensure DB helper exists
from pathlib import Path
app_dir = ROOT / "app"
app_dir.mkdir(exist_ok=True)

db_path1 = ROOT / "app" / "database.py"
db_path2 = ROOT / "app" / "db" / "session.py"
if not db_path1.exists() and not db_path2.exists():
    db_text = '''import os
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from app.db.base import Base

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./trendy.db")
engine = create_engine(DATABASE_URL, echo=False, future=True)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
'''
    (ROOT / "app" / "database.py").write_text(db_text)
    print("Created app/database.py")
else:
    print("app/database.py or app/db/session.py exists — skipping creation")

# 2) Ensure Redis client exists
redis_client = ROOT / "app" / "services" / "redis_client.py"
redis_client.parent.mkdir(parents=True, exist_ok=True)
redis_text = '''import os
import redis
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379")

def get_redis_client():
    return redis.from_url(REDIS_URL, decode_responses=True)
'''
redis_client.write_text(redis_text)
print("Ensured redis client at", redis_client)

# 3) Create hybrid feed if missing
feed_service = ROOT / "app" / "services" / "hybrid_feed.py"
if not feed_service.exists():
    feed_service_text = '''from app.services.personalization_service import PersonalizationService
from app.services.trend_service import TrendService
from app.services.analytics_event_service import AnalyticsEventService
from app.services.redis_client import get_redis_client

class HybridFeedEngine:
    def __init__(self, db):
        self.db = db
        self.personalization = PersonalizationService(db)
        self.trend = TrendService(db)
        self.analytics = AnalyticsEventService(db)
        self.redis = get_redis_client()

    def discover_feed(self, user_id=None, limit=20):
        cache_key = f"feed:discover:{user_id or 'anon'}:{limit}"
        try:
            cached = self.redis.get(cache_key)
        except Exception:
            cached = None
        if cached:
            try:
                return eval(cached)
            except Exception:
                pass
        personalized = []
        try:
            personalized = self.personalization.recommend_for_user(user_id, limit=limit//2) if user_id else []
        except Exception:
            personalized = []
        trending = []
        try:
            trending = self.trend.get_trending_content(limit=limit - len(personalized))
        except Exception:
            trending = []
        results = []
        added = set()
        for p in personalized:
            cid = p.get("content_id")
            if cid and cid not in added:
                results.append({"content_id": cid, "score": p.get("score",0), "reason":"personalized"})
                added.add(cid)
        for t in trending:
            if t.get("content_id") not in added:
                results.append({"content_id": t.get("content_id"), "score": t.get("score",0), "reason":"trending"})
                added.add(t.get("content_id"))
            if len(results) >= limit:
                break
        try:
            self.redis.setex(cache_key, 60, str(results))
        except Exception:
            pass
        return results
'''
    feed_service.write_text(feed_service_text)
    print("Created HybridFeedEngine at", feed_service)
else:
    print("Hybrid feed exists — skipping")

# 4) Ensure moderation service exists
moderation = ROOT / "app" / "services" / "moderation_engine.py"
if not moderation.exists():
    moderation.write_text('''import random
class AIModerationService:
    def analyze_text(self, text):
        bad = ["kill","nude","terror","bomb"]
        flags = [w for w in bad if w in (text or "").lower()]
        score = min(1.0, len(flags) * 0.5)
        return {"approved": score < 0.6, "flags": flags, "score": score}

    def analyze_file(self, filename):
        return {"approved": True, "score": 0.1, "flags": []}
''')
    print("Created AIModerationService placeholder")
else:
    print("Moderation service exists — skipping")

# 5) Flutter config
flutter_config = ROOT.parent / "trendy" / "lib" / "config.dart"
flutter_config.parent.mkdir(parents=True, exist_ok=True)
flutter_config.write_text('''// Auto-generated config to point Flutter app to backend API
class AppConfig {
  static const String API_BASE = String.fromEnvironment("API_BASE", defaultValue: "http://10.0.2.2:8000/api/v1");
  static const String FIREBASE_OPTIONS_JSON = "trendy-83364-firebase-adminsdk-fbsvc-1a3dbe98af.json";
}
''')
print("Wrote Flutter config.dart at", flutter_config)

# 6) Verification script
scripts_dir = ROOT / "scripts"
scripts_dir.mkdir(parents=True, exist_ok=True)
verify_script = scripts_dir / "verify_system.py"
verify_script.write_text('''import sys, traceback
from app.database import engine, SessionLocal
from app.database import get_db
print("=== Verify DB connect ===")
try:
    db = SessionLocal()
    from sqlalchemy import text
    res = db.execute(text("SELECT 1"))
    print("DB OK", res.scalar())
except Exception as e:
    print("DB ERROR", e)
finally:
    try:
        db.close()
    except Exception:
        pass

print("=== Verify imports ===")
try:
    import app.services.hybrid_feed as hf
    import app.services.moderation_engine as mod
    print("Imports OK")
except Exception as e:
    print("Import ERROR")
    traceback.print_exc()
''')
print("Created verification script:", verify_script)

# 7) Run quick checks
try:
    print("Running backend verification script...")
    sh(f"{sys.executable} {verify_script}", check=False)
except Exception as e:
    print("Verification script error:", e)
    traceback.print_exc()

print("=== FINALIZATION SCRIPT completed ===")
